apiVersion: v1
kind: Namespace
metadata:
  name: agentshield
  labels:
    app.kubernetes.io/name: agentshield
    app.kubernetes.io/part-of: agentshield-waf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agentshield-config
  namespace: agentshield
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "agentshield"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  TOOL_CUSTOMER_URL: "http://tools-service:8001"
  TOOL_EMAIL_URL: "http://tools-service:8002"
  TOOL_FILE_URL: "http://tools-service:8003"
---
apiVersion: v1
kind: Secret
metadata:
  name: agentshield-secrets
  namespace: agentshield
type: Opaque
stringData:
  POSTGRES_USER: "agentshield"
  POSTGRES_PASSWORD: "agentshield_production_secure_pass_2026"
  SECRET_KEY: "prod-jwt-and-signing-secret-key-change-in-vault"
  WAF_API_KEY: "prod-admin-api-key-agentshield-2026"
