"""Initial schema - agents, tools, policies, audit_events, sessions

Revision ID: 287801bc5273
Revises:
Create Date: 2026-08-18 21:15:39.544747
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "287801bc5273"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("actions_performed", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_sessions_agent_id"), "agent_sessions", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_sessions_session_id"),
        "agent_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("api_key_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_agent_id"), "agents", ["agent_id"], unique=True)
    op.create_index(op.f("ix_agents_policy_id"), "agents", ["policy_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=True),
        sa.Column("parameters_sanitised", sa.JSON(), nullable=True),
        sa.Column("rules_evaluated", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("blocked_by_rule", sa.String(length=64), nullable=True),
        sa.Column("policy_id", sa.String(length=128), nullable=True),
        sa.Column("policy_version", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("tool_response_status", sa.Integer(), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_agent_created",
        "audit_events",
        ["agent_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_audit_agent_tool", "audit_events", ["agent_id", "tool"], unique=False)
    op.create_index(
        "ix_audit_decision_created",
        "audit_events",
        ["decision", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_events_agent_id"), "audit_events", ["agent_id"], unique=False)
    op.create_index(op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_events_decision"), "audit_events", ["decision"], unique=False)
    op.create_index(op.f("ix_audit_events_event_id"), "audit_events", ["event_id"], unique=True)
    op.create_index(op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False)
    op.create_index(op.f("ix_audit_events_session_id"), "audit_events", ["session_id"], unique=False)
    op.create_index(op.f("ix_audit_events_tool"), "audit_events", ["tool"], unique=False)
    op.create_table(
        "policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("policy_config", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policies_policy_id"), "policies", ["policy_id"], unique=True)
    op.create_table(
        "tools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("endpoint_url", sa.String(length=512), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parameters_schema", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tools_tool_id"), "tools", ["tool_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tools_tool_id"), table_name="tools")
    op.drop_table("tools")
    op.drop_index(op.f("ix_policies_policy_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_audit_events_tool"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_session_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_decision"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_agent_id"), table_name="audit_events")
    op.drop_index("ix_audit_decision_created", table_name="audit_events")
    op.drop_index("ix_audit_agent_tool", table_name="audit_events")
    op.drop_index("ix_audit_agent_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_agents_policy_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_agent_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_agent_sessions_session_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_agent_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
